# Generated by Django 6.0 on 2025-12-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuerpoPertenencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del cuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('numero_registro', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Número de registro')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(max_length=100, verbose_name='Segundo apellido')),
                ('dni', models.CharField(max_length=9, unique=True, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion_postal', models.CharField(max_length=255, verbose_name='Dirección postal')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Código postal')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('contrasena', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('estado_hermano', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja')], default='ACTIVO', max_length=10, verbose_name='Estado del hermano')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADA', 'Pagada'), ('EXENTO', 'Exento de pago')], default='PENDIENTE', max_length=20, verbose_name='Estado de pago')),
                ('es_admin', models.BooleanField(default=False, verbose_name='Es administrador')),
                ('cuerpos', models.ManyToManyField(blank=True, related_name='hermanos', to='api.cuerpopertenencia', verbose_name='Cuerpos de pertenencia')),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('tipo_comunicacion', models.CharField(choices=[('ACUERDO_CABILDO', 'Acuerdos de cabildos'), ('CONVOCATORIA_CABILDO', 'Convocatorias de cabildo'), ('NOTICIA', 'Noticias'), ('COMUNICADO', 'Comunicados'), ('FOTOGALERIA', 'Fotogalería')], default='NOTICIA', max_length=30, verbose_name='Tipo de comunicación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados', to='api.hermano', verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='PapeletaSitio',
            fields=[
                ('numero_papeleta', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de papeleta')),
                ('estado_papeleta', models.CharField(choices=[('NO_SOLICITADA', 'No solicitada'), ('SOLICITADA', 'Solicitada'), ('EMITIDA', 'Emitida'), ('RECOGIDA', 'Recogida')], default='NO_SOLICITADA', max_length=20, verbose_name='Estado de la papeleta')),
                ('fecha_emision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('codigo_verificacion', models.CharField(max_length=100, unique=True, verbose_name='Código de verificación')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('lugar_citacion', models.CharField(max_length=255, verbose_name='Lugar de citación')),
                ('hora_citacion', models.TimeField(verbose_name='Hora de citacion')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeletas', to='api.hermano', verbose_name='Hermano')),
            ],
        ),
    ]
