# Generated by Django 6.0 on 2025-12-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cuerpopertenencia_hermano_comunicado_papeletasitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CARIDAD', 'Caridad'), ('CULTOS_FORMACION', 'Cultos y Formación'), ('JUVENTUD', 'Juventud (Grupo Joven)'), ('PATRIMONIO', 'Patrimonio'), ('PRIOSTIA', 'Priostía'), ('DIPUTACION MAYOR GOBIERNO', 'Diputación mayor de gobierno'), ('COSTALEROS', 'Costaleros'), ('ACOLITOS', 'Cuerpo de acólitos')], max_length=50, unique=True, verbose_name='Nombre del área')),
            ],
        ),
        migrations.AlterField(
            model_name='cuerpopertenencia',
            name='nombre',
            field=models.CharField(choices=[('COSTALEROS', 'Costaleros'), ('NAZARENOS', 'Nazarenos'), ('DIPUTADOS_TRAMO', 'Diputados de tramo'), ('BRAZALETES', 'Brazaletes'), ('ACOLITOS', 'Cuerpo de acólitos'), ('CAPATAZ', 'Capataz'), ('SANITARIOS', 'Sanitarios'), ('PRIOSTIA', 'Priostía'), ('CARIDAD', 'Caridad y acción social'), ('JUVENTUD', 'Juventud'), ('JUNTA_GOBIERNO', 'Junta de gobierno')], max_length=50, unique=True, verbose_name='Nombre del cuerpo'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='areas_interes',
            field=models.ManyToManyField(blank=True, related_name='hermanos', to='api.areainteres', verbose_name='Áreas de interés'),
        ),
    ]
