# Generated by Django 6.0 on 2025-12-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_areainteres_alter_cuerpopertenencia_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='destinatarios',
            field=models.ManyToManyField(help_text='Seleccione las áreas de interés a las que va dirigido este comunicado', related_name='comunicados_recibidos', to='api.areainteres', verbose_name='Áreas destinatarias'),
        ),
    ]
