# Generated by Django 6.0 on 2025-12-28 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comunicado_destinatarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del acto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha del acto')),
                ('tipo_acto', models.CharField(choices=[('ESTACION_PENITENCIA', 'Estación de Penitencia'), ('CABILDO_GENERAL', 'Cabildo General de Hermanos'), ('CABILDO_EXTRAORDINARIO', 'Cabildo Extraordinario de Hermanos'), ('VIA_CRUCIS', 'Vía Crucis'), ('QUINARIO', 'Quinario'), ('TRIDUO', 'Triduo'), ('ROSARIO_AURORA', 'Rosario de la Aurora')], max_length=30, verbose_name='Tipo de acto')),
            ],
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='acto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papeletas_generadas', to='api.acto', verbose_name='Acto'),
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del puesto')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo (Tramo, Insignia, etc.)')),
                ('numero_maximo_asignaciones', models.PositiveIntegerField(verbose_name='Máximo de asignaciones')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Está disponible?')),
                ('acto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='api.acto', verbose_name='Acto')),
            ],
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeletas_asignadas', to='api.puesto', verbose_name='Puesto'),
        ),
    ]
