# Generated by Django 6.0 on 2025-12-28 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_acto_papeletasitio_acto_puesto_papeletasitio_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ESTACION_PENITENCIA', 'Estación de Penitencia'), ('CABILDO_GENERAL', 'Cabildo General de Hermanos'), ('CABILDO_EXTRAORDINARIO', 'Cabildo Extraordinario de Hermanos'), ('VIA_CRUCIS', 'Vía Crucis'), ('QUINARIO', 'Quinario'), ('TRIDUO', 'Triduo'), ('ROSARIO_AURORA', 'Rosario de la Aurora')], max_length=100, unique=True, verbose_name='Nombre del tipo de acto')),
                ('requiere_papeleta', models.BooleanField(default=True, verbose_name='¿Requiere papeleta de sitio?')),
                ('cuerpos_requeridos', models.ManyToManyField(blank=True, related_name='tipos_acto_permitidos', to='api.cuerpopertenencia', verbose_name='Cuerpos requeridos/permitidos')),
            ],
        ),
        migrations.AlterField(
            model_name='acto',
            name='tipo_acto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actos', to='api.tipoacto', verbose_name='Tipo de acto'),
        ),
    ]
