# Generated by Django 6.0 on 2025-12-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tipoacto_alter_acto_tipo_acto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuerpopertenencia',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tipoacto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cuerpopertenencia',
            name='nombre_cuerpo',
            field=models.CharField(blank=True, choices=[('COSTALEROS', 'Costaleros'), ('NAZARENOS', 'Nazarenos'), ('DIPUTADOS_TRAMO', 'Diputados de tramo'), ('BRAZALETES', 'Brazaletes'), ('ACOLITOS', 'Cuerpo de acólitos'), ('CAPATACES', 'Capataces'), ('SANITARIOS', 'Sanitarios'), ('PRIOSTIA', 'Priostía'), ('CARIDAD', 'Caridad y acción social'), ('JUVENTUD', 'Juventud'), ('JUNTA_GOBIERNO', 'Junta de gobierno')], max_length=50, null=True, unique=True, verbose_name='Nombre del cuerpo'),
        ),
        migrations.AddField(
            model_name='tipoacto',
            name='tipo',
            field=models.CharField(choices=[('ESTACION_PENITENCIA', 'Estación de Penitencia'), ('CABILDO_GENERAL', 'Cabildo General de Hermanos'), ('CABILDO_EXTRAORDINARIO', 'Cabildo Extraordinario de Hermanos'), ('VIA_CRUCIS', 'Vía Crucis'), ('QUINARIO', 'Quinario'), ('TRIDUO', 'Triduo'), ('ROSARIO_AURORA', 'Rosario de la Aurora'), ('CONVIVENCIA', 'Convivencia')], default='CONVIVENCIA', max_length=100, unique=True, verbose_name='Nombre del tipo de acto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papeletasitio',
            name='estado_papeleta',
            field=models.CharField(choices=[('NO_SOLICITADA', 'No solicitada'), ('SOLICITADA', 'Solicitada'), ('EMITIDA', 'Emitida'), ('RECOGIDA', 'Recogida'), ('LEIDA', 'Leída'), ('ANULADA', 'Anulada')], default='NO_SOLICITADA', max_length=20, verbose_name='Estado de la papeleta'),
        ),
    ]
